bonapart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls')),
    path('users/', include('users.urls'), name='users'),
    path('apartments/', include('apartments.urls'), name='apartments'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'users.views.error_404_view'

users/urls.py
from django.urls import path
from users.views import *
from django.contrib.auth.views import LogoutView


app_name = 'users'

urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('notifications/', NotificationView.as_view(), name='notifications'),
    path('mark_notification_as_read/<int:notification_id>/', mark_notification_as_read, name='mark_notification_as_read'),
    path('my-apartments/', UserApartmentsListView.as_view(), name='my-apartments'),
    path('delete_profile/', DeleteProfileView.as_view(), name='delete_profile'),

    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('clear_favorites/', ClearFavoritesView.as_view(), name='clear_favorites'),
    path('pending/', ApartmentPendingListView.as_view(), name='apartment_pending'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('stock', StockView.as_view(), name='stock'),
    path('collaboration', CollaborationView.as_view(), name='collaboration'),
    path('transfers', TransfersView.as_view(), name='transfers'),
    path('about', AboutView.as_view(), name='about'),
    path('privacy_policy', PrivacyPolicy.as_view(), name='privacy_policy'),
    path('terms', Terms.as_view(), name='terms'),
    path('support', Support.as_view(), name='support')

]

templates/signin.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="light"><head>
	<title>BonApart - Аренда квартир.</title>

	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="bonapart.com">
	<meta name="description" content="BonApart - Аренда квартир.">



	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static 'images/logo.jpg' %}">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&amp;family=Poppins:wght@400;500;700&amp;display=swap">

	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-icons.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/tiny-slider.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/glightbox.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/flatpickr.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/choices.min.css' %}">
	<!-- Theme CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <style>
        .btn.btn-primary.mb-0 {
          background-color: #169916;
          border-color: #169916;
        }
    </style>

</head>


<body>

<!-- **************** MAIN CONTENT START **************** -->
<main>

<!-- =======================
Main Content START -->
<section class="vh-xxl-100">
	<div class="container h-100 d-flex px-0 px-sm-4">
		<div class="row justify-content-center align-items-center m-auto">
			<div class="col-12">
				<div class="bg-mode shadow rounded-3 overflow-hidden">
					<div class="row g-0">
						<!-- Vector Image -->
						<div class="col-lg-6 d-flex align-items-center order-2 order-lg-1">
							<div class="p-3 p-lg-5">
								<img src="{% static 'images/signin.svg' %}" alt="">
							</div>
							<!-- Divider -->
							<div class="vr opacity-1 d-none d-lg-block"></div>
						</div>

						<!-- Information -->
						<div class="col-lg-6 order-1">
							<div class="p-4 p-sm-7">
								<!-- Logo -->
								<a class="navbar-brand d-flex align-items-center justify-content-center mb-4" href="{% url 'website:home' %}">
                                    <img style="border-radius: 50px; width: 50px;" class="light-mode-item navbar-brand-item" src="{% static 'images/logo.jpg' %}" alt="logo">
                                    <p style="margin: 0; padding: 0; margin-left: 8px; font-size: 30px; color: black;"><b>BonApart</b></p>
                                </a>

								<!-- Title -->
								<h1 class="mb-2 h3" style="text-align: center;">Добро пожаловать!</h1>
								<p class="mb-0">Нет аккаунта?<a href="{% url 'users:signup' %}"> Создать аккаунт!</a></p>

								<!-- Form START -->
								<form class="mt-4 text-start" method="post">
									{% csrf_token %}
									{{ form.as_p }}

									<div class="mb-3 d-sm-flex justify-content-between">
										<div>
											<input type="checkbox" class="form-check-input" id="rememberCheck">
											<label class="form-check-label" for="rememberCheck">Запомнить меня</label>
										</div>
										<a href="#">Забыли пароль?</a>
									</div>
									<!-- Button -->
									<div><button type="submit" class="btn btn-primary w-100 mb-0">Войти</button></div>



									<!-- Copyright -->
									<div class="text-primary-hover text-body mt-3 text-center"> Copyrights ©2023 BonApart. Создал <a href="http://workbenchkz.pythonanywhere.com/" class="text-body">WorkBench</a>. </div>
								</form>
								<!-- Form END -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- =======================
Main Content END -->

</main>


<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- ThemeFunctions -->
<script src="{% static 'js/functions.js' %}"></script>


</body></html>

templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="light">
<head>
	<title>BonApart - Аренда квартир.</title>

	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="bonapart.com">
	<meta name="description" content="BonApart - Аренда квартир.">

	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static 'images/logo.jpg' %}">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&amp;family=Poppins:wght@400;500;700&amp;display=swap">

	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-icons.css' %}">

	<!-- Theme CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <style>
        .btn.btn-primary.mb-0 {
          background-color: #169916;
          border-color: #169916;
        }
    </style>

</head>

<body>

<!-- **************** MAIN CONTENT START **************** -->
<main>

<!-- =======================
Main Content START -->
<section class="vh-xxl-100">
	<div class="container h-100 d-flex px-0 px-sm-4">
		<div class="row justify-content-center align-items-center m-auto">
			<div class="col-12">
				<div class="bg-mode shadow rounded-3 overflow-hidden">
					<div class="row g-0">
						<!-- Vector Image -->
						<div class="col-lg-6 d-md-flex align-items-center order-2 order-lg-1">
							<div class="p-3 p-lg-5">
								<img src="{% static 'images/signin.svg' %}" alt="">
							</div>
							<!-- Divider -->
							<div class="vr opacity-1 d-none d-lg-block"></div>
						</div>

						<!-- Information -->
						<div class="col-lg-6 order-1">
							<div class="p-4 p-sm-6">
								<!-- Logo -->
								<a class="navbar-brand d-flex align-items-center justify-content-center mb-4" href="{% url 'website:home' %}">
                                    <img style="border-radius: 50px; width: 50px;" class="light-mode-item navbar-brand-item" src="{% static 'images/logo.jpg' %}" alt="logo">
                                    <p style="margin: 0; padding: 0; margin-left: 8px; font-size: 30px; color: black;"><b>BonApart</b></p>
                                </a>
								<!-- Title -->
								<h1 class="mb-2 h3">Новый аккаунт</h1>
								<p class="mb-0">Есть аккаунт?<a href="{% url 'users:signin' %}"> Войти</a></p>

								<!-- Form START -->
								<form class="mt-4 text-start" method="post">
									{% csrf_token %}
										{{ form.as_p }}
									<!-- Remember me -->
									<div class="mb-3">
										<input type="checkbox" class="form-check-input" id="rememberCheck">
										<label class="form-check-label" for="rememberCheck">Запомнить меня</label>
									</div>
									<!-- Button -->
									<div><button type="submit" class="btn btn-primary w-100 mb-0">Зарегистрироваться</button></div>

									<!-- Copyright -->
									<div class="text-primary-hover text-body mt-3 text-center"> Copyrights ©2023 BonApart. Создал <a href="http://workbenchkz.pythonanywhere.com/" class="text-body">WorkBench</a>. </div>
								</form>
								<!-- Form END -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- =======================
Main Content END -->

</main>

<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- ThemeFunctions -->
<script src="{% static 'js/functions.js' %}"></script>


</body></html>